dashboard/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('shopping/', views.shopping, name='shopping'),
    path('reminders/', views.reminder, name='reminders'),
    path('roster/', views.roster, name='roster'),
    path('', RedirectView.as_view(url='shopping/', permanent=True)),
]

flat_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', RedirectView.as_view(url='/dashboard/', permanent=True)),
]


# !!!!!! delete for production
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

flat_dashboard/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Flatdash</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark
         {% block nav-style %}{% endblock %}">
      <a class="navbar-brand" href="#">Yolkplace</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{% url 'dashboard:shopping' %}">Shopping</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'dashboard:reminders' %}">Reminders</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'dashboard:roster' %}">Roster</a></li>
            {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
            {% endif %}
        </ul>
      </div>
    </nav>
</header>
<div class="container">
    <br>
    {% block page_content %}{% endblock %}

</div>
<footer>
<div class= "navbar navbar-inverse navbar-static-bottom" role="navigation">
    <div class="navbar-text pull-left">
    </div>
    <div class= "navbar-text pull-right">
    </div>
    <div class="navbar-text pull-left">
    {% if user.is_authenticated %}
      Hi {{ user.username }}!
    {% else %}
      <p>You are not logged in</p>
    {% endif %}
    </div>
</div>
</footer>
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>